/*
// one JSON method
var binds = [
  { "bind": "key_esc", "title": "", "action": "", "color": "" },
  { "bind": "key_f1", "title": "", "action": "", "color": "" },
  { "bind": "key_f2", "title": "", "action": "", "color": "" },
  { "bind": "key_f3", "title": "", "action": "", "color": "" },
  { "bind": "key_f4", "title": "", "action": "", "color": "" },
  { "bind": "key_f5", "title": "", "action": "", "color": "" },
  { "bind": "key_f6", "title": "", "action": "", "color": "" },
  { "bind": "key_f7", "title": "", "action": "", "color": "" },
  { "bind": "key_f8", "title": "", "action": "", "color": "" },
  { "bind": "key_f9", "title": "", "action": "", "color": "" },
  { "bind": "key_f10", "title": "", "action": "", "color": "" },
  { "bind": "key_f11", "title": "", "action": "", "color": "" },
  { "bind": "key_f12", "title": "", "action": "", "color": "" },
  { "bind": "key_backtick", "title": "", "action": "", "color": "" },
  { "bind": "key_1", "title": "", "action": "", "color": "" },
  { "bind": "key_2", "title": "", "action": "", "color": "" },
  { "bind": "key_3", "title": "", "action": "", "color": "" },
  { "bind": "key_4", "title": "", "action": "", "color": "" },
  { "bind": "key_5", "title": "", "action": "", "color": "" },
  { "bind": "key_6", "title": "", "action": "", "color": "" },
  { "bind": "key_7", "title": "", "action": "", "color": "" },
  { "bind": "key_8", "title": "", "action": "", "color": "" },
  { "bind": "key_9", "title": "", "action": "", "color": "" },
  { "bind": "key_0", "title": "", "action": "", "color": "" },
  { "bind": "key_minus", "title": "", "action": "", "color": "" },
  { "bind": "key_plus", "title": "", "action": "", "color": "" },
  { "bind": "key_backspace", "title": "", "action": "", "color": "" },
  { "bind": "key_tab", "title": "", "action": "", "color": "" },
  { "bind": "key_q", "title": "", "action": "", "color": "" },
  { "bind": "key_w", "title": "", "action": "", "color": "" },
  { "bind": "key_e", "title": "", "action": "", "color": "" },
  { "bind": "key_r", "title": "", "action": "", "color": "" },
  { "bind": "key_t", "title": "", "action": "", "color": "" },
  { "bind": "key_y", "title": "", "action": "", "color": "" },
  { "bind": "key_u", "title": "", "action": "", "color": "" },
  { "bind": "key_i", "title": "", "action": "", "color": "" },
  { "bind": "key_o", "title": "", "action": "", "color": "" },
  { "bind": "key_p", "title": "", "action": "", "color": "" },
  { "bind": "key_left_bracket", "title": "", "action": "", "color": "" },
  { "bind": "key_right_bracket", "title": "", "action": "", "color": "" },
  { "bind": "key_backslash", "title": "", "action": "", "color": "" },
  { "bind": "key_caps_lock", "title": "", "action": "", "color": "" },
  { "bind": "key_a", "title": "", "action": "", "color": "" },
  { "bind": "key_s", "title": "", "action": "", "color": "" },
  { "bind": "key_d", "title": "", "action": "", "color": "" },
  { "bind": "key_f", "title": "", "action": "", "color": "" },
  { "bind": "key_g", "title": "", "action": "", "color": "" },
  { "bind": "key_h", "title": "", "action": "", "color": "" },
  { "bind": "key_j", "title": "", "action": "", "color": "" },
  { "bind": "key_k", "title": "", "action": "", "color": "" },
  { "bind": "key_l", "title": "", "action": "", "color": "" },
  { "bind": "key_semicolon", "title": "", "action": "", "color": "" },
  { "bind": "key_apostrophe", "title": "", "action": "", "color": "" },
  { "bind": "key_enter", "title": "", "action": "", "color": "" },
  { "bind": "key_left_shift", "title": "", "action": "", "color": "" },
  { "bind": "key_z", "title": "", "action": "", "color": "" },
  { "bind": "key_x", "title": "", "action": "", "color": "" },
  { "bind": "key_c", "title": "", "action": "", "color": "" },
  { "bind": "key_v", "title": "", "action": "", "color": "" },
  { "bind": "key_b", "title": "", "action": "", "color": "" },
  { "bind": "key_n", "title": "", "action": "", "color": "" },
  { "bind": "key_m", "title": "", "action": "", "color": "" },
  { "bind": "key_comma", "title": "", "action": "", "color": "" },
  { "bind": "key_period", "title": "", "action": "", "color": "" },
  { "bind": "key_forwardslash", "title": "", "action": "", "color": "" },
  { "bind": "key_right_shift", "title": "", "action": "", "color": "" },
  { "bind": "key_left_ctrl", "title": "", "action": "", "color": "" },
  { "bind": "key_left_special", "title": "", "action": "", "color": "" },
  { "bind": "key_left_alt", "title": "", "action": "", "color": "" },
  { "bind": "key_space_bar", "title": "", "action": "", "color": "" },
  { "bind": "key_right_alt", "title": "", "action": "", "color": "" },
  { "bind": "key_right_special", "title": "", "action": "", "color": "" },
  { "bind": "key_popup", "title": "", "action": "", "color": "" },
  { "bind": "key_right_ctrl", "title": "", "action": "", "color": "" },
  { "bind": "key_prtscr", "title": "", "action": "", "color": "" },
  { "bind": "key_scrlck", "title": "", "action": "", "color": "" },
  { "bind": "key_pause", "title": "", "action": "", "color": "" },
  { "bind": "key_insert", "title": "", "action": "", "color": "" },
  { "bind": "key_home", "title": "", "action": "", "color": "" },
  { "bind": "key_page_up", "title": "", "action": "", "color": "" },
  { "bind": "key_delete", "title": "", "action": "", "color": "" },
  { "bind": "key_end", "title": "", "action": "", "color": "" },
  { "bind": "key_page_down", "title": "", "action": "", "color": "" },
  { "bind": "key_up", "title": "", "action": "", "color": "" },
  { "bind": "key_left", "title": "", "action": "", "color": "" },
  { "bind": "key_down", "title": "", "action": "", "color": "" },
  { "bind": "key_right", "title": "", "action": "", "color": "" },
  { "bind": "key_num_lock", "title": "", "action": "", "color": "" },
  { "bind": "key_num_slash", "title": "", "action": "", "color": "" },
  { "bind": "key_num_multiply", "title": "", "action": "", "color": "" },
  { "bind": "key_num_minus", "title": "", "action": "", "color": "" },
  { "bind": "key_num_7", "title": "", "action": "", "color": "" },
  { "bind": "key_num_8", "title": "", "action": "", "color": "" },
  { "bind": "key_num_9", "title": "", "action": "", "color": "" },
  { "bind": "key_num_plus", "title": "", "action": "", "color": "" },
  { "bind": "key_num_6", "title": "", "action": "", "color": "" },
  { "bind": "key_num_5", "title": "", "action": "", "color": "" },
  { "bind": "key_num_4", "title": "", "action": "", "color": "" },
  { "bind": "key_num_1", "title": "", "action": "", "color": "" },
  { "bind": "key_num_2", "title": "", "action": "", "color": "" },
  { "bind": "key_num_3", "title": "", "action": "", "color": "" },
  { "bind": "key_num_enter", "title": "", "action": "", "color": "" },
  { "bind": "key_num_period", "title": "", "action": "", "color": "" },
  { "bind": "key_num_0", "title": "", "action": "", "color": "" },
  { "bind": "mouse_1", "title": "", "action": "", "color": "" },
  { "bind": "mouse_2", "title": "", "action": "", "color": "" },
  { "bind": "mouse_3", "title": "", "action": "", "color": "" },
  { "bind": "mouse_4", "title": "", "action": "", "color": "" },
  { "bind": "mouse_5", "title": "", "action": "", "color": "" },
  { "bind": "mouse_6", "title": "", "action": "", "color": "" },
  { "bind": "mouse_7", "title": "", "action": "", "color": "" },
  { "bind": "mouse_wheel_up", "title": "", "action": "", "color": "" },
  { "bind": "mouse_wheel_down", "title": "", "action": "", "color": "" }
];

binds.forEach(function(e, i, a) {
  console.log(e);
});
*/

// I like this one better
var binds = [
  { "key_esc": { "title": "menu", "action": "", "color": "" } },
  { "key_f1": { "title": "", "action": "", "color": "" } },
  { "key_f2": { "title": "", "action": "", "color": "" } },
  { "key_f3": { "title": "", "action": "", "color": "" } },
  { "key_f4": { "title": "", "action": "", "color": "" } },
  { "key_f5": { "title": "", "action": "", "color": "" } },
  { "key_f6": { "title": "", "action": "", "color": "" } },
  { "key_f7": { "title": "", "action": "", "color": "" } },
  { "key_f8": { "title": "", "action": "", "color": "" } },
  { "key_f9": { "title": "", "action": "", "color": "" } },
  { "key_f10": { "title": "", "action": "", "color": "" } },
  { "key_f11": { "title": "", "action": "", "color": "" } },
  { "key_f12": { "title": "", "action": "", "color": "" } },
  { "key_backtick": { "title": "", "action": "", "color": "" } },
  { "key_1": { "title": "", "action": "", "color": "" } },
  { "key_2": { "title": "", "action": "", "color": "" } },
  { "key_3": { "title": "", "action": "", "color": "" } },
  { "key_4": { "title": "", "action": "", "color": "" } },
  { "key_5": { "title": "", "action": "", "color": "" } },
  { "key_6": { "title": "", "action": "", "color": "" } },
  { "key_7": { "title": "", "action": "", "color": "" } },
  { "key_8": { "title": "", "action": "", "color": "" } },
  { "key_9": { "title": "", "action": "", "color": "" } },
  { "key_0": { "title": "", "action": "", "color": "" } },
  { "key_minus": { "title": "", "action": "", "color": "" } },
  { "key_plus": { "title": "", "action": "", "color": "" } },
  { "key_backspace": { "title": "", "action": "", "color": "" } },
  { "key_tab": { "title": "", "action": "", "color": "" } },
  { "key_q": { "title": "", "action": "", "color": "" } },
  { "key_w": { "title": "", "action": "", "color": "" } },
  { "key_e": { "title": "", "action": "", "color": "" } },
  { "key_r": { "title": "", "action": "", "color": "" } },
  { "key_t": { "title": "", "action": "", "color": "" } },
  { "key_y": { "title": "", "action": "", "color": "" } },
  { "key_u": { "title": "", "action": "", "color": "" } },
  { "key_i": { "title": "", "action": "", "color": "" } },
  { "key_o": { "title": "", "action": "", "color": "" } },
  { "key_p": { "title": "", "action": "", "color": "" } },
  { "key_left_bracket": { "title": "", "action": "", "color": "" } },
  { "key_right_bracket": { "title": "", "action": "", "color": "" } },
  { "key_backslash": { "title": "", "action": "", "color": "" } },
  { "key_caps_lock": { "title": "", "action": "", "color": "" } },
  { "key_a": { "title": "", "action": "", "color": "" } },
  { "key_s": { "title": "", "action": "", "color": "" } },
  { "key_d": { "title": "", "action": "", "color": "" } },
  { "key_f": { "title": "", "action": "", "color": "" } },
  { "key_g": { "title": "", "action": "", "color": "" } },
  { "key_h": { "title": "", "action": "", "color": "" } },
  { "key_j": { "title": "", "action": "", "color": "" } },
  { "key_k": { "title": "", "action": "", "color": "" } },
  { "key_l": { "title": "", "action": "", "color": "" } },
  { "key_semicolon": { "title": "", "action": "", "color": "" } },
  { "key_apostrophe": { "title": "", "action": "", "color": "" } },
  { "key_enter": { "title": "", "action": "", "color": "" } },
  { "key_left_shift": { "title": "", "action": "", "color": "" } },
  { "key_z": { "title": "", "action": "", "color": "" } },
  { "key_x": { "title": "", "action": "", "color": "" } },
  { "key_c": { "title": "", "action": "", "color": "" } },
  { "key_v": { "title": "", "action": "", "color": "" } },
  { "key_b": { "title": "", "action": "", "color": "" } },
  { "key_n": { "title": "", "action": "", "color": "" } },
  { "key_m": { "title": "", "action": "", "color": "" } },
  { "key_comma": { "title": "", "action": "", "color": "" } },
  { "key_period": { "title": "", "action": "", "color": "" } },
  { "key_forwardslash": { "title": "", "action": "", "color": "" } },
  { "key_right_shift": { "title": "", "action": "", "color": "" } },
  { "key_left_ctrl": { "title": "", "action": "", "color": "" } },
  { "key_left_special": { "title": "", "action": "", "color": "" } },
  { "key_left_alt": { "title": "", "action": "", "color": "" } },
  { "key_space_bar": { "title": "", "action": "", "color": "" } },
  { "key_right_alt": { "title": "", "action": "", "color": "" } },
  { "key_right_special": { "title": "", "action": "", "color": "" } },
  { "key_popup": { "title": "", "action": "", "color": "" } },
  { "key_right_ctrl": { "title": "", "action": "", "color": "" } },
  { "key_prtscr": { "title": "", "action": "", "color": "" } },
  { "key_scrlck": { "title": "", "action": "", "color": "" } },
  { "key_pause": { "title": "", "action": "", "color": "" } },
  { "key_insert": { "title": "", "action": "", "color": "" } },
  { "key_home": { "title": "", "action": "", "color": "" } },
  { "key_page_up": { "title": "", "action": "", "color": "" } },
  { "key_delete": { "title": "", "action": "", "color": "" } },
  { "key_end": { "title": "", "action": "", "color": "" } },
  { "key_page_down": { "title": "", "action": "", "color": "" } },
  { "key_up": { "title": "", "action": "", "color": "" } },
  { "key_left": { "title": "", "action": "", "color": "" } },
  { "key_down": { "title": "", "action": "", "color": "" } },
  { "key_right": { "title": "", "action": "", "color": "" } },
  { "key_num_lock": { "title": "", "action": "", "color": "" } },
  { "key_num_slash": { "title": "", "action": "", "color": "" } },
  { "key_num_multiply": { "title": "", "action": "", "color": "" } },
  { "key_num_minus": { "title": "", "action": "", "color": "" } },
  { "key_num_7": { "title": "", "action": "", "color": "" } },
  { "key_num_8": { "title": "", "action": "", "color": "" } },
  { "key_num_9": { "title": "", "action": "", "color": "" } },
  { "key_num_plus": { "title": "", "action": "", "color": "" } },
  { "key_num_6": { "title": "", "action": "", "color": "" } },
  { "key_num_5": { "title": "", "action": "", "color": "" } },
  { "key_num_4": { "title": "", "action": "", "color": "" } },
  { "key_num_1": { "title": "", "action": "", "color": "" } },
  { "key_num_2": { "title": "", "action": "", "color": "" } },
  { "key_num_3": { "title": "", "action": "", "color": "" } },
  { "key_num_enter": { "title": "", "action": "", "color": "" } },
  { "key_num_period": { "title": "", "action": "", "color": "" } },
  { "key_num_0": { "title": "", "action": "", "color": "" } },
  { "mouse_1": { "title": "", "action": "", "color": "" } },
  { "mouse_2": { "title": "", "action": "", "color": "" } },
  { "mouse_3": { "title": "", "action": "", "color": "" } },
  { "mouse_4": { "title": "", "action": "", "color": "" } },
  { "mouse_5": { "title": "", "action": "", "color": "" } },
  { "mouse_6": { "title": "", "action": "", "color": "" } },
  { "mouse_7": { "title": "", "action": "", "color": "" } },
  { "mouse_wheel_up": { "title": "", "action": "", "color": "" } },
  { "mouse_wheel_down": { "title": "", "action": "", "color": "" } }
];

binds.forEach(function(e, i, a) {
  var bind = Object.keys(e)[0];
  console.log(bind);
  console.log(e[bind].title);
  console.log(e[Object.keys(e)[0]]);
  var div = document.getElementById(bind);
  console.log(div.innerHTML);
});

